/**
 * Seeded Swedish grocery catalog — the tiles a household taps to build a
 * shopping list. Names are Swedish, singular, lowercase except proper nouns
 * (a few canned/frozen products are conventionally plural on Swedish
 * packaging — e.g. "krossade tomater", "kidneybönor" — and are kept that way
 * since that is the actual product name, not a grammatical slip).
 *
 * `iconRef` is an emoji codepoint (uppercase hex, no "U+" prefix; sequences
 * join with "-"). It is mechanically derived from `emoji` — see
 * seed-data.test.ts, which asserts the two never drift apart.
 *
 * `hasAtHome` marks true pantry staples a recipe should NOT add to a list by
 * default (salt, spices, flour, baking staples, cooking oil, ...).
 */

export interface SeedItem {
  name: string;
  categorySlug: string;
  iconRef: string;
  emoji: string;
  hasAtHome?: boolean;
}

export const CATALOG_ITEMS: SeedItem[] = [
  { name: "äpple", categorySlug: "frukt-gront", iconRef: "1F34E", emoji: "🍎" },
  { name: "banan", categorySlug: "frukt-gront", iconRef: "1F34C", emoji: "🍌" },
  { name: "apelsin", categorySlug: "frukt-gront", iconRef: "1F34A", emoji: "🍊" },
  { name: "clementin", categorySlug: "frukt-gront", iconRef: "1F34A", emoji: "🍊" },
  { name: "grapefrukt", categorySlug: "frukt-gront", iconRef: "1F34A", emoji: "🍊" },
  { name: "citron", categorySlug: "frukt-gront", iconRef: "1F34B", emoji: "🍋" },
  { name: "lime", categorySlug: "frukt-gront", iconRef: "1F34B", emoji: "🍋" },
  { name: "päron", categorySlug: "frukt-gront", iconRef: "1F350", emoji: "🍐" },
  { name: "vindruvor", categorySlug: "frukt-gront", iconRef: "1F347", emoji: "🍇" },
  { name: "avokado", categorySlug: "frukt-gront", iconRef: "1F951", emoji: "🥑" },
  { name: "ananas", categorySlug: "frukt-gront", iconRef: "1F34D", emoji: "🍍" },
  { name: "mango", categorySlug: "frukt-gront", iconRef: "1F96D", emoji: "🥭" },
  { name: "kiwi", categorySlug: "frukt-gront", iconRef: "1F95D", emoji: "🥝" },
  { name: "jordgubbar", categorySlug: "frukt-gront", iconRef: "1F353", emoji: "🍓" },
  { name: "blåbär", categorySlug: "frukt-gront", iconRef: "1FAD0", emoji: "🫐" },
  { name: "hallon", categorySlug: "frukt-gront", iconRef: "1FAD0", emoji: "🫐" },
  { name: "björnbär", categorySlug: "frukt-gront", iconRef: "1FAD0", emoji: "🫐" },
  { name: "vattenmelon", categorySlug: "frukt-gront", iconRef: "1F349", emoji: "🍉" },
  { name: "melon", categorySlug: "frukt-gront", iconRef: "1F348", emoji: "🍈" },
  { name: "persika", categorySlug: "frukt-gront", iconRef: "1F351", emoji: "🍑" },
  { name: "nektarin", categorySlug: "frukt-gront", iconRef: "1F351", emoji: "🍑" },
  { name: "plommon", categorySlug: "frukt-gront", iconRef: "1F351", emoji: "🍑" },
  { name: "körsbär", categorySlug: "frukt-gront", iconRef: "1F352", emoji: "🍒" },
  { name: "tomat", categorySlug: "frukt-gront", iconRef: "1F345", emoji: "🍅" },
  { name: "körsbärstomat", categorySlug: "frukt-gront", iconRef: "1F345", emoji: "🍅" },
  { name: "gurka", categorySlug: "frukt-gront", iconRef: "1F952", emoji: "🥒" },
  { name: "isbergssallad", categorySlug: "frukt-gront", iconRef: "1F96C", emoji: "🥬" },
  { name: "morot", categorySlug: "frukt-gront", iconRef: "1F955", emoji: "🥕" },
  { name: "gul lök", categorySlug: "frukt-gront", iconRef: "1F9C5", emoji: "🧅" },
  { name: "rödlök", categorySlug: "frukt-gront", iconRef: "1F9C5", emoji: "🧅" },
  { name: "vitlök", categorySlug: "frukt-gront", iconRef: "1F9C4", emoji: "🧄" },
  { name: "potatis", categorySlug: "frukt-gront", iconRef: "1F954", emoji: "🥔" },
  { name: "paprika", categorySlug: "frukt-gront", iconRef: "1FAD1", emoji: "🫑" },
  { name: "broccoli", categorySlug: "frukt-gront", iconRef: "1F966", emoji: "🥦" },
  { name: "blomkål", categorySlug: "frukt-gront", iconRef: "1F966", emoji: "🥦" },
  { name: "zucchini", categorySlug: "frukt-gront", iconRef: "1F952", emoji: "🥒" },
  { name: "aubergine", categorySlug: "frukt-gront", iconRef: "1F346", emoji: "🍆" },
  { name: "purjolök", categorySlug: "frukt-gront", iconRef: "1F9C5", emoji: "🧅" },
  { name: "rödbeta", categorySlug: "frukt-gront", iconRef: "1F955", emoji: "🥕" },
  { name: "vitkål", categorySlug: "frukt-gront", iconRef: "1F96C", emoji: "🥬" },
  { name: "spenat", categorySlug: "frukt-gront", iconRef: "1F96C", emoji: "🥬" },
  { name: "majs", categorySlug: "frukt-gront", iconRef: "1F33D", emoji: "🌽" },
  { name: "champinjon", categorySlug: "frukt-gront", iconRef: "1F344", emoji: "🍄" },
  { name: "ingefära", categorySlug: "frukt-gront", iconRef: "1FADA", emoji: "🫚" },
  { name: "chili", categorySlug: "frukt-gront", iconRef: "1F336-FE0F", emoji: "🌶️" },
  { name: "persilja", categorySlug: "frukt-gront", iconRef: "1F33F", emoji: "🌿" },
  { name: "formbröd", categorySlug: "brod", iconRef: "1F35E", emoji: "🍞" },
  { name: "fralla", categorySlug: "brod", iconRef: "1F35E", emoji: "🍞" },
  { name: "baguette", categorySlug: "brod", iconRef: "1F956", emoji: "🥖" },
  { name: "surdegsbröd", categorySlug: "brod", iconRef: "1F35E", emoji: "🍞" },
  { name: "rågbröd", categorySlug: "brod", iconRef: "1F35E", emoji: "🍞" },
  { name: "knäckebröd", categorySlug: "brod", iconRef: "1F35E", emoji: "🍞" },
  { name: "tunnbröd", categorySlug: "brod", iconRef: "1FAD3", emoji: "🫓" },
  { name: "ströbröd", categorySlug: "brod", iconRef: "1F35E", emoji: "🍞" },
  { name: "pitabröd", categorySlug: "brod", iconRef: "1FAD3", emoji: "🫓" },
  { name: "tortillabröd", categorySlug: "brod", iconRef: "1FAD3", emoji: "🫓" },
  { name: "hamburgerbröd", categorySlug: "brod", iconRef: "1F35E", emoji: "🍞" },
  { name: "korvbröd", categorySlug: "brod", iconRef: "1F35E", emoji: "🍞" },
  { name: "skorpor", categorySlug: "brod", iconRef: "1F35E", emoji: "🍞" },
  { name: "polarbröd", categorySlug: "brod", iconRef: "1FAD3", emoji: "🫓" },
  { name: "mjölk", categorySlug: "mejeri-agg", iconRef: "1F95B", emoji: "🥛" },
  { name: "lättmjölk", categorySlug: "mejeri-agg", iconRef: "1F95B", emoji: "🥛" },
  { name: "mellanmjölk", categorySlug: "mejeri-agg", iconRef: "1F95B", emoji: "🥛" },
  { name: "havredryck", categorySlug: "mejeri-agg", iconRef: "1F95B", emoji: "🥛" },
  { name: "mandeldryck", categorySlug: "mejeri-agg", iconRef: "1F95B", emoji: "🥛" },
  { name: "vispgrädde", categorySlug: "mejeri-agg", iconRef: "1F95B", emoji: "🥛" },
  { name: "matlagningsgrädde", categorySlug: "mejeri-agg", iconRef: "1F95B", emoji: "🥛" },
  { name: "crème fraiche", categorySlug: "mejeri-agg", iconRef: "1F95B", emoji: "🥛" },
  { name: "gräddfil", categorySlug: "mejeri-agg", iconRef: "1F95B", emoji: "🥛" },
  { name: "filmjölk", categorySlug: "mejeri-agg", iconRef: "1F95B", emoji: "🥛" },
  { name: "yoghurt", categorySlug: "mejeri-agg", iconRef: "1F95B", emoji: "🥛" },
  { name: "kvarg", categorySlug: "mejeri-agg", iconRef: "1F95B", emoji: "🥛" },
  { name: "keso", categorySlug: "mejeri-agg", iconRef: "1F95B", emoji: "🥛" },
  { name: "smör", categorySlug: "mejeri-agg", iconRef: "1F9C8", emoji: "🧈", hasAtHome: true },
  { name: "margarin", categorySlug: "mejeri-agg", iconRef: "1F9C8", emoji: "🧈" },
  { name: "ost", categorySlug: "mejeri-agg", iconRef: "1F9C0", emoji: "🧀" },
  { name: "kryddost", categorySlug: "mejeri-agg", iconRef: "1F9C0", emoji: "🧀" },
  { name: "västerbottensost", categorySlug: "mejeri-agg", iconRef: "1F9C0", emoji: "🧀" },
  { name: "messmör", categorySlug: "mejeri-agg", iconRef: "1F9C8", emoji: "🧈" },
  { name: "ägg", categorySlug: "mejeri-agg", iconRef: "1F95A", emoji: "🥚" },
  { name: "parmesan", categorySlug: "mejeri-agg", iconRef: "1F9C0", emoji: "🧀" },
  { name: "mozzarella", categorySlug: "mejeri-agg", iconRef: "1F9C0", emoji: "🧀" },
  { name: "skinka", categorySlug: "chark-palagg", iconRef: "1F953", emoji: "🥓" },
  { name: "kokt skinka", categorySlug: "chark-palagg", iconRef: "1F953", emoji: "🥓" },
  { name: "rostbiff", categorySlug: "chark-palagg", iconRef: "1F953", emoji: "🥓" },
  { name: "kalkonpålägg", categorySlug: "chark-palagg", iconRef: "1F953", emoji: "🥓" },
  { name: "salami", categorySlug: "chark-palagg", iconRef: "1F953", emoji: "🥓" },
  { name: "chorizo", categorySlug: "chark-palagg", iconRef: "1F953", emoji: "🥓" },
  { name: "falukorv", categorySlug: "chark-palagg", iconRef: "1F32D", emoji: "🌭" },
  { name: "prinskorv", categorySlug: "chark-palagg", iconRef: "1F32D", emoji: "🌭" },
  { name: "wienerkorv", categorySlug: "chark-palagg", iconRef: "1F32D", emoji: "🌭" },
  { name: "leverpastej", categorySlug: "chark-palagg", iconRef: "1F96B", emoji: "🥫" },
  { name: "kaviar", categorySlug: "chark-palagg", iconRef: "1F96B", emoji: "🥫" },
  { name: "bacon", categorySlug: "chark-palagg", iconRef: "1F953", emoji: "🥓" },
  { name: "prosciutto", categorySlug: "chark-palagg", iconRef: "1F953", emoji: "🥓" },
  { name: "blodpudding", categorySlug: "chark-palagg", iconRef: "1F37D-FE0F", emoji: "🍽️" },
  { name: "mortadella", categorySlug: "chark-palagg", iconRef: "1F953", emoji: "🥓" },
  { name: "pepperoni", categorySlug: "chark-palagg", iconRef: "1F953", emoji: "🥓" },
  { name: "sylta", categorySlug: "chark-palagg", iconRef: "1F37D-FE0F", emoji: "🍽️" },
  { name: "leverkorv", categorySlug: "chark-palagg", iconRef: "1F32D", emoji: "🌭" },
  { name: "julskinka", categorySlug: "chark-palagg", iconRef: "1F953", emoji: "🥓" },
  { name: "kabanoss", categorySlug: "chark-palagg", iconRef: "1F32D", emoji: "🌭" },
  { name: "kycklingfilé", categorySlug: "kott-fagel", iconRef: "1F357", emoji: "🍗" },
  { name: "kycklinglårfilé", categorySlug: "kott-fagel", iconRef: "1F357", emoji: "🍗" },
  { name: "hel kyckling", categorySlug: "kott-fagel", iconRef: "1F357", emoji: "🍗" },
  { name: "nötfärs", categorySlug: "kott-fagel", iconRef: "1F969", emoji: "🥩" },
  { name: "fläskfärs", categorySlug: "kott-fagel", iconRef: "1F969", emoji: "🥩" },
  { name: "blandfärs", categorySlug: "kott-fagel", iconRef: "1F969", emoji: "🥩" },
  { name: "köttbullar", categorySlug: "kott-fagel", iconRef: "1F958", emoji: "🥘" },
  { name: "fläskkotlett", categorySlug: "kott-fagel", iconRef: "1F969", emoji: "🥩" },
  { name: "fläskfilé", categorySlug: "kott-fagel", iconRef: "1F969", emoji: "🥩" },
  { name: "entrecote", categorySlug: "kott-fagel", iconRef: "1F969", emoji: "🥩" },
  { name: "innerfilé", categorySlug: "kott-fagel", iconRef: "1F969", emoji: "🥩" },
  { name: "ytterfilé", categorySlug: "kott-fagel", iconRef: "1F969", emoji: "🥩" },
  { name: "karré", categorySlug: "kott-fagel", iconRef: "1F969", emoji: "🥩" },
  { name: "lammkotlett", categorySlug: "kott-fagel", iconRef: "1F969", emoji: "🥩" },
  { name: "lammfärs", categorySlug: "kott-fagel", iconRef: "1F969", emoji: "🥩" },
  { name: "kalkonfilé", categorySlug: "kott-fagel", iconRef: "1F357", emoji: "🍗" },
  { name: "revbensspjäll", categorySlug: "kott-fagel", iconRef: "1F356", emoji: "🍖" },
  { name: "råbiffar", categorySlug: "kott-fagel", iconRef: "1F969", emoji: "🥩" },
  { name: "lax", categorySlug: "fisk-skaldjur", iconRef: "1F41F", emoji: "🐟" },
  { name: "torsk", categorySlug: "fisk-skaldjur", iconRef: "1F41F", emoji: "🐟" },
  { name: "räkor", categorySlug: "fisk-skaldjur", iconRef: "1F364", emoji: "🍤" },
  { name: "sill", categorySlug: "fisk-skaldjur", iconRef: "1F41F", emoji: "🐟" },
  { name: "senapssill", categorySlug: "fisk-skaldjur", iconRef: "1F41F", emoji: "🐟" },
  { name: "surströmming", categorySlug: "fisk-skaldjur", iconRef: "1F41F", emoji: "🐟" },
  { name: "fiskpinnar", categorySlug: "fisk-skaldjur", iconRef: "1F41F", emoji: "🐟" },
  { name: "fiskbullar", categorySlug: "fisk-skaldjur", iconRef: "1F41F", emoji: "🐟" },
  { name: "musslor", categorySlug: "fisk-skaldjur", iconRef: "1F9AA", emoji: "🦪" },
  { name: "kräftor", categorySlug: "fisk-skaldjur", iconRef: "1F99E", emoji: "🦞" },
  { name: "tonfisk", categorySlug: "fisk-skaldjur", iconRef: "1F96B", emoji: "🥫" },
  { name: "rökt lax", categorySlug: "fisk-skaldjur", iconRef: "1F41F", emoji: "🐟" },
  { name: "gravlax", categorySlug: "fisk-skaldjur", iconRef: "1F41F", emoji: "🐟" },
  { name: "panerad fisk", categorySlug: "fisk-skaldjur", iconRef: "1F41F", emoji: "🐟" },
  { name: "lasagne", categorySlug: "fardigmat", iconRef: "1F371", emoji: "🍱" },
  { name: "färdigsallad", categorySlug: "fardigmat", iconRef: "1F957", emoji: "🥗" },
  { name: "sushi", categorySlug: "fardigmat", iconRef: "1F363", emoji: "🍣" },
  { name: "wrap", categorySlug: "fardigmat", iconRef: "1F32F", emoji: "🌯" },
  { name: "soppa", categorySlug: "fardigmat", iconRef: "1F372", emoji: "🍲" },
  { name: "pyttipanna", categorySlug: "fardigmat", iconRef: "1F371", emoji: "🍱" },
  { name: "currygryta", categorySlug: "fardigmat", iconRef: "1F35B", emoji: "🍛" },
  { name: "pastasallad", categorySlug: "fardigmat", iconRef: "1F35D", emoji: "🍝" },
  { name: "kebabtallrik", categorySlug: "fardigmat", iconRef: "1F371", emoji: "🍱" },
  { name: "falafel", categorySlug: "fardigmat", iconRef: "1F9C6", emoji: "🧆" },
  { name: "quiche", categorySlug: "fardigmat", iconRef: "1F967", emoji: "🥧" },
  { name: "gratäng", categorySlug: "fardigmat", iconRef: "1F371", emoji: "🍱" },
  { name: "glass", categorySlug: "fryst", iconRef: "1F368", emoji: "🍨" },
  { name: "frysta bär", categorySlug: "fryst", iconRef: "1FAD0", emoji: "🫐" },
  { name: "fryst pizza", categorySlug: "fryst", iconRef: "1F355", emoji: "🍕" },
  { name: "pommes frites", categorySlug: "fryst", iconRef: "1F35F", emoji: "🍟" },
  { name: "frysta ärter", categorySlug: "fryst", iconRef: "1FADB", emoji: "🫛" },
  { name: "fryst majs", categorySlug: "fryst", iconRef: "1F33D", emoji: "🌽" },
  { name: "fryst spenat", categorySlug: "fryst", iconRef: "1F96C", emoji: "🥬" },
  { name: "fryst grönsaksblandning", categorySlug: "fryst", iconRef: "1F966", emoji: "🥦" },
  { name: "isbitar", categorySlug: "fryst", iconRef: "1F9CA", emoji: "🧊" },
  { name: "frysta räkor", categorySlug: "fryst", iconRef: "1F364", emoji: "🍤" },
  { name: "glasspinnar", categorySlug: "fryst", iconRef: "1F366", emoji: "🍦" },
  { name: "fryst smördeg", categorySlug: "fryst", iconRef: "1F950", emoji: "🥐" },
  { name: "frysta bullar", categorySlug: "fryst", iconRef: "1F950", emoji: "🥐" },
  { name: "fryst smoothieblandning", categorySlug: "fryst", iconRef: "1F353", emoji: "🍓" },
  { name: "kycklingnuggets", categorySlug: "fryst", iconRef: "1F357", emoji: "🍗" },
  { name: "frysta köttbullar", categorySlug: "fryst", iconRef: "1F958", emoji: "🥘" },
  { name: "krossade tomater", categorySlug: "skafferi", iconRef: "1F96B", emoji: "🥫" },
  { name: "tomatpuré", categorySlug: "skafferi", iconRef: "1F96B", emoji: "🥫" },
  { name: "passerade tomater", categorySlug: "skafferi", iconRef: "1F96B", emoji: "🥫" },
  { name: "kokosmjölk", categorySlug: "skafferi", iconRef: "1F965", emoji: "🥥" },
  { name: "buljongtärningar", categorySlug: "skafferi", iconRef: "1F9C2", emoji: "🧂", hasAtHome: true },
  { name: "matolja", categorySlug: "skafferi", iconRef: "1FAD7", emoji: "🫗", hasAtHome: true },
  { name: "olivolja", categorySlug: "skafferi", iconRef: "1FAD7", emoji: "🫗", hasAtHome: true },
  { name: "ättika", categorySlug: "skafferi", iconRef: "1F376", emoji: "🍶", hasAtHome: true },
  { name: "soja", categorySlug: "skafferi", iconRef: "1FAD7", emoji: "🫗" },
  { name: "senap", categorySlug: "skafferi", iconRef: "1FAD9", emoji: "🫙" },
  { name: "ketchup", categorySlug: "skafferi", iconRef: "1FAD9", emoji: "🫙" },
  { name: "majonnäs", categorySlug: "skafferi", iconRef: "1FAD9", emoji: "🫙" },
  { name: "bearnaisesås", categorySlug: "skafferi", iconRef: "1FAD9", emoji: "🫙" },
  { name: "barbecuesås", categorySlug: "skafferi", iconRef: "1FAD9", emoji: "🫙" },
  { name: "chilisås", categorySlug: "skafferi", iconRef: "1F336-FE0F", emoji: "🌶️" },
  { name: "pesto", categorySlug: "skafferi", iconRef: "1FAD9", emoji: "🫙" },
  { name: "kikärtor", categorySlug: "skafferi", iconRef: "1F96B", emoji: "🥫" },
  { name: "kidneybönor", categorySlug: "skafferi", iconRef: "1F96B", emoji: "🥫" },
  { name: "potatismos", categorySlug: "skafferi", iconRef: "1F954", emoji: "🥔" },
  { name: "vita bönor", categorySlug: "skafferi", iconRef: "1F96B", emoji: "🥫" },
  { name: "linser", categorySlug: "skafferi", iconRef: "1F96B", emoji: "🥫" },
  { name: "russin", categorySlug: "skafferi", iconRef: "1F4E6", emoji: "📦" },
  { name: "nötter", categorySlug: "skafferi", iconRef: "1F95C", emoji: "🥜" },
  { name: "jordnötssmör", categorySlug: "skafferi", iconRef: "1F95C", emoji: "🥜" },
  { name: "honung", categorySlug: "skafferi", iconRef: "1F36F", emoji: "🍯" },
  { name: "lingonsylt", categorySlug: "skafferi", iconRef: "1F353", emoji: "🍓" },
  { name: "saft", categorySlug: "skafferi", iconRef: "1F9C3", emoji: "🧃" },
  { name: "salt", categorySlug: "skafferi", iconRef: "1F9C2", emoji: "🧂", hasAtHome: true },
  { name: "peppar", categorySlug: "skafferi", iconRef: "1F9C2", emoji: "🧂", hasAtHome: true },
  { name: "kanel", categorySlug: "skafferi", iconRef: "1F9C2", emoji: "🧂", hasAtHome: true },
  { name: "kardemumma", categorySlug: "skafferi", iconRef: "1F9C2", emoji: "🧂", hasAtHome: true },
  { name: "muskot", categorySlug: "skafferi", iconRef: "1F9C2", emoji: "🧂", hasAtHome: true },
  { name: "oregano", categorySlug: "skafferi", iconRef: "1F9C2", emoji: "🧂", hasAtHome: true },
  { name: "torkad basilika", categorySlug: "skafferi", iconRef: "1F9C2", emoji: "🧂", hasAtHome: true },
  { name: "timjan", categorySlug: "skafferi", iconRef: "1F9C2", emoji: "🧂", hasAtHome: true },
  { name: "paprikapulver", categorySlug: "skafferi", iconRef: "1F9C2", emoji: "🧂", hasAtHome: true },
  { name: "curry", categorySlug: "skafferi", iconRef: "1F9C2", emoji: "🧂", hasAtHome: true },
  { name: "chilipulver", categorySlug: "skafferi", iconRef: "1F9C2", emoji: "🧂", hasAtHome: true },
  { name: "vitlökspulver", categorySlug: "skafferi", iconRef: "1F9C2", emoji: "🧂", hasAtHome: true },
  { name: "lagerblad", categorySlug: "skafferi", iconRef: "1F9C2", emoji: "🧂", hasAtHome: true },
  { name: "torkad dill", categorySlug: "skafferi", iconRef: "1F9C2", emoji: "🧂", hasAtHome: true },
  { name: "saffran", categorySlug: "skafferi", iconRef: "1F9C2", emoji: "🧂" },
  { name: "spaghetti", categorySlug: "pasta-ris-gryn", iconRef: "1F35D", emoji: "🍝" },
  { name: "pasta", categorySlug: "pasta-ris-gryn", iconRef: "1F35D", emoji: "🍝" },
  { name: "lasagneplattor", categorySlug: "pasta-ris-gryn", iconRef: "1F35D", emoji: "🍝" },
  { name: "jasminris", categorySlug: "pasta-ris-gryn", iconRef: "1F35A", emoji: "🍚" },
  { name: "basmatiris", categorySlug: "pasta-ris-gryn", iconRef: "1F35A", emoji: "🍚" },
  { name: "grötris", categorySlug: "pasta-ris-gryn", iconRef: "1F35A", emoji: "🍚" },
  { name: "couscous", categorySlug: "pasta-ris-gryn", iconRef: "1F35A", emoji: "🍚" },
  { name: "bulgur", categorySlug: "pasta-ris-gryn", iconRef: "1F35A", emoji: "🍚" },
  { name: "quinoa", categorySlug: "pasta-ris-gryn", iconRef: "1F35A", emoji: "🍚" },
  { name: "havregryn", categorySlug: "pasta-ris-gryn", iconRef: "1F33E", emoji: "🌾" },
  { name: "bovete", categorySlug: "pasta-ris-gryn", iconRef: "1F33E", emoji: "🌾" },
  { name: "polenta", categorySlug: "pasta-ris-gryn", iconRef: "1F33D", emoji: "🌽" },
  { name: "nudlar", categorySlug: "pasta-ris-gryn", iconRef: "1F35C", emoji: "🍜" },
  { name: "glasnudlar", categorySlug: "pasta-ris-gryn", iconRef: "1F35C", emoji: "🍜" },
  { name: "vetemjöl", categorySlug: "bak-mjol", iconRef: "1F33E", emoji: "🌾", hasAtHome: true },
  { name: "rågmjöl", categorySlug: "bak-mjol", iconRef: "1F33E", emoji: "🌾" },
  { name: "havremjöl", categorySlug: "bak-mjol", iconRef: "1F33E", emoji: "🌾" },
  { name: "potatismjöl", categorySlug: "bak-mjol", iconRef: "1F33E", emoji: "🌾" },
  { name: "mandelmjöl", categorySlug: "bak-mjol", iconRef: "1F33E", emoji: "🌾" },
  { name: "grahamsmjöl", categorySlug: "bak-mjol", iconRef: "1F33E", emoji: "🌾" },
  { name: "socker", categorySlug: "bak-mjol", iconRef: "1F9C2", emoji: "🧂", hasAtHome: true },
  { name: "florsocker", categorySlug: "bak-mjol", iconRef: "1F9C2", emoji: "🧂" },
  { name: "farinsocker", categorySlug: "bak-mjol", iconRef: "1F9C2", emoji: "🧂" },
  { name: "vaniljsocker", categorySlug: "bak-mjol", iconRef: "1F9C2", emoji: "🧂", hasAtHome: true },
  { name: "bakpulver", categorySlug: "bak-mjol", iconRef: "1F9C2", emoji: "🧂", hasAtHome: true },
  { name: "bikarbonat", categorySlug: "bak-mjol", iconRef: "1F9C2", emoji: "🧂", hasAtHome: true },
  { name: "jäst", categorySlug: "bak-mjol", iconRef: "1F35E", emoji: "🍞" },
  { name: "kakao", categorySlug: "bak-mjol", iconRef: "1F36B", emoji: "🍫" },
  { name: "bakchoklad", categorySlug: "bak-mjol", iconRef: "1F36B", emoji: "🍫" },
  { name: "mandel", categorySlug: "bak-mjol", iconRef: "1F95C", emoji: "🥜" },
  { name: "kokosflingor", categorySlug: "bak-mjol", iconRef: "1F965", emoji: "🥥" },
  { name: "muffinsform", categorySlug: "bak-mjol", iconRef: "1F9C1", emoji: "🧁" },
  { name: "bakplåtspapper", categorySlug: "bak-mjol", iconRef: "1F9FB", emoji: "🧻" },
  { name: "pärlsocker", categorySlug: "bak-mjol", iconRef: "1F9C2", emoji: "🧂" },
  { name: "bryggkaffe", categorySlug: "kaffe-te", iconRef: "2615", emoji: "☕" },
  { name: "snabbkaffe", categorySlug: "kaffe-te", iconRef: "2615", emoji: "☕" },
  { name: "kaffebönor", categorySlug: "kaffe-te", iconRef: "2615", emoji: "☕" },
  { name: "kaffekapslar", categorySlug: "kaffe-te", iconRef: "2615", emoji: "☕" },
  { name: "svart te", categorySlug: "kaffe-te", iconRef: "1F375", emoji: "🍵" },
  { name: "grönt te", categorySlug: "kaffe-te", iconRef: "1F375", emoji: "🍵" },
  { name: "rooibos te", categorySlug: "kaffe-te", iconRef: "1F375", emoji: "🍵" },
  { name: "chai te", categorySlug: "kaffe-te", iconRef: "1F375", emoji: "🍵" },
  { name: "koffeinfritt kaffe", categorySlug: "kaffe-te", iconRef: "2615", emoji: "☕" },
  { name: "O'boy", categorySlug: "kaffe-te", iconRef: "1F36B", emoji: "🍫" },
  { name: "chips", categorySlug: "snacks-godis", iconRef: "1F35F", emoji: "🍟" },
  { name: "chokladkaka", categorySlug: "snacks-godis", iconRef: "1F36B", emoji: "🍫" },
  { name: "lösgodis", categorySlug: "snacks-godis", iconRef: "1F36C", emoji: "🍬" },
  { name: "lakrits", categorySlug: "snacks-godis", iconRef: "1F36C", emoji: "🍬" },
  { name: "tuggummi", categorySlug: "snacks-godis", iconRef: "1F36C", emoji: "🍬" },
  { name: "popcorn", categorySlug: "snacks-godis", iconRef: "1F37F", emoji: "🍿" },
  { name: "saltade jordnötter", categorySlug: "snacks-godis", iconRef: "1F95C", emoji: "🥜" },
  { name: "kex", categorySlug: "snacks-godis", iconRef: "1F36A", emoji: "🍪" },
  { name: "wienerbröd", categorySlug: "snacks-godis", iconRef: "1F950", emoji: "🥐" },
  { name: "kanelbulle", categorySlug: "snacks-godis", iconRef: "1F950", emoji: "🥐" },
  { name: "saltstänger", categorySlug: "snacks-godis", iconRef: "1F968", emoji: "🥨" },
  { name: "ostbågar", categorySlug: "snacks-godis", iconRef: "1F9C0", emoji: "🧀" },
  { name: "dammsugare", categorySlug: "snacks-godis", iconRef: "1F36B", emoji: "🍫" },
  { name: "kola", categorySlug: "snacks-godis", iconRef: "1F36C", emoji: "🍬" },
  { name: "marshmallows", categorySlug: "snacks-godis", iconRef: "1F36C", emoji: "🍬" },
  { name: "pepparkakor", categorySlug: "snacks-godis", iconRef: "1F36A", emoji: "🍪" },
  { name: "läsk", categorySlug: "dryck", iconRef: "1F964", emoji: "🥤" },
  { name: "lättläsk", categorySlug: "dryck", iconRef: "1F964", emoji: "🥤" },
  { name: "festis", categorySlug: "dryck", iconRef: "1F9C3", emoji: "🧃" },
  { name: "julmust", categorySlug: "dryck", iconRef: "1F964", emoji: "🥤" },
  { name: "apelsinjuice", categorySlug: "dryck", iconRef: "1F9C3", emoji: "🧃" },
  { name: "äppeljuice", categorySlug: "dryck", iconRef: "1F9C3", emoji: "🧃" },
  { name: "mineralvatten", categorySlug: "dryck", iconRef: "1F4A7", emoji: "💧" },
  { name: "vatten", categorySlug: "dryck", iconRef: "1F4A7", emoji: "💧" },
  { name: "energidryck", categorySlug: "dryck", iconRef: "1F964", emoji: "🥤" },
  { name: "sportdryck", categorySlug: "dryck", iconRef: "1F964", emoji: "🥤" },
  { name: "folköl", categorySlug: "dryck", iconRef: "1F37A", emoji: "🍺" },
  { name: "alkoholfri öl", categorySlug: "dryck", iconRef: "1F37A", emoji: "🍺" },
  { name: "kombucha", categorySlug: "dryck", iconRef: "1F9C3", emoji: "🧃" },
  { name: "proteindryck", categorySlug: "dryck", iconRef: "1F964", emoji: "🥤" },
  { name: "smoothie", categorySlug: "dryck", iconRef: "1F9C3", emoji: "🧃" },
  { name: "chokladmjölk", categorySlug: "dryck", iconRef: "1F95B", emoji: "🥛" },
  { name: "nyponsoppa", categorySlug: "dryck", iconRef: "1F963", emoji: "🥣" },
  { name: "äppelmust", categorySlug: "dryck", iconRef: "1F9C3", emoji: "🧃" },
  { name: "diskmedel", categorySlug: "hushall", iconRef: "1F9F4", emoji: "🧴" },
  { name: "diskborste", categorySlug: "hushall", iconRef: "1F9FD", emoji: "🧽" },
  { name: "diskmaskinstabletter", categorySlug: "hushall", iconRef: "1F9F4", emoji: "🧴" },
  { name: "tvättmedel", categorySlug: "hushall", iconRef: "1F9F4", emoji: "🧴" },
  { name: "sköljmedel", categorySlug: "hushall", iconRef: "1F9F4", emoji: "🧴" },
  { name: "toapapper", categorySlug: "hushall", iconRef: "1F9FB", emoji: "🧻" },
  { name: "hushållspapper", categorySlug: "hushall", iconRef: "1F9FB", emoji: "🧻" },
  { name: "soppåsar", categorySlug: "hushall", iconRef: "1F5D1-FE0F", emoji: "🗑️" },
  { name: "matavfallspåsar", categorySlug: "hushall", iconRef: "1F5D1-FE0F", emoji: "🗑️" },
  { name: "aluminiumfolie", categorySlug: "hushall", iconRef: "1F4E6", emoji: "📦" },
  { name: "plastfolie", categorySlug: "hushall", iconRef: "1F4E6", emoji: "📦" },
  { name: "fryspåsar", categorySlug: "hushall", iconRef: "1F4E6", emoji: "📦" },
  { name: "engångsmatlådor", categorySlug: "hushall", iconRef: "1F4E6", emoji: "📦" },
  { name: "allrent", categorySlug: "hushall", iconRef: "1F9F4", emoji: "🧴" },
  { name: "fönsterputs", categorySlug: "hushall", iconRef: "1F9F4", emoji: "🧴" },
  { name: "wc-rent", categorySlug: "hushall", iconRef: "1F9F4", emoji: "🧴" },
  { name: "disksvamp", categorySlug: "hushall", iconRef: "1F9FD", emoji: "🧽" },
  { name: "engångshandskar", categorySlug: "hushall", iconRef: "1F9E4", emoji: "🧤" },
  { name: "batterier", categorySlug: "hushall", iconRef: "1F50B", emoji: "🔋" },
  { name: "stearinljus", categorySlug: "hushall", iconRef: "1F56F-FE0F", emoji: "🕯️" },
  { name: "tandkräm", categorySlug: "hygien", iconRef: "1F9F4", emoji: "🧴" },
  { name: "tandborste", categorySlug: "hygien", iconRef: "1FAA5", emoji: "🪥" },
  { name: "tvål", categorySlug: "hygien", iconRef: "1F9FC", emoji: "🧼" },
  { name: "duschtvål", categorySlug: "hygien", iconRef: "1F9F4", emoji: "🧴" },
  { name: "schampo", categorySlug: "hygien", iconRef: "1F9F4", emoji: "🧴" },
  { name: "balsam", categorySlug: "hygien", iconRef: "1F9F4", emoji: "🧴" },
  { name: "deodorant", categorySlug: "hygien", iconRef: "1F9F4", emoji: "🧴" },
  { name: "rakhyvel", categorySlug: "hygien", iconRef: "1FA92", emoji: "🪒" },
  { name: "bindor", categorySlug: "hygien", iconRef: "1F9F4", emoji: "🧴" },
  { name: "tamponger", categorySlug: "hygien", iconRef: "1F9F4", emoji: "🧴" },
  { name: "plåster", categorySlug: "hygien", iconRef: "1FA79", emoji: "🩹" },
  { name: "solkräm", categorySlug: "hygien", iconRef: "1F9F4", emoji: "🧴" },
  { name: "handsprit", categorySlug: "hygien", iconRef: "1F9F4", emoji: "🧴" },
  { name: "våtservetter", categorySlug: "hygien", iconRef: "1F9FB", emoji: "🧻" },
  { name: "blöjor", categorySlug: "barn", iconRef: "1F9F7", emoji: "🧷" },
  { name: "barnmat", categorySlug: "barn", iconRef: "1F37C", emoji: "🍼" },
  { name: "välling", categorySlug: "barn", iconRef: "1F37C", emoji: "🍼" },
  { name: "blöjpåsar", categorySlug: "barn", iconRef: "1F4E6", emoji: "📦" },
  { name: "barnschampo", categorySlug: "barn", iconRef: "1F9F4", emoji: "🧴" },
  { name: "nappar", categorySlug: "barn", iconRef: "1F37C", emoji: "🍼" },
  { name: "grötpulver", categorySlug: "barn", iconRef: "1F37C", emoji: "🍼" },
  { name: "fruktpuré", categorySlug: "barn", iconRef: "1F37C", emoji: "🍼" },
  { name: "hundmat", categorySlug: "djur", iconRef: "1F436", emoji: "🐶" },
  { name: "kattmat", categorySlug: "djur", iconRef: "1F431", emoji: "🐱" },
  { name: "kattsand", categorySlug: "djur", iconRef: "1F431", emoji: "🐱" },
  { name: "hundgodis", categorySlug: "djur", iconRef: "1F436", emoji: "🐶" },
  { name: "fågelfrö", categorySlug: "djur", iconRef: "1F426", emoji: "🐦" },
  { name: "fiskfoder", categorySlug: "djur", iconRef: "1F420", emoji: "🐠" },
  { name: "tändstickor", categorySlug: "ovrigt", iconRef: "1F525", emoji: "🔥" },
  { name: "engångsgrill", categorySlug: "ovrigt", iconRef: "1F525", emoji: "🔥" },
  { name: "blommor", categorySlug: "ovrigt", iconRef: "1F490", emoji: "💐" },
  { name: "tidning", categorySlug: "ovrigt", iconRef: "1F4F0", emoji: "📰" },
  { name: "servetter", categorySlug: "ovrigt", iconRef: "1F9FB", emoji: "🧻" },
  { name: "ballonger", categorySlug: "ovrigt", iconRef: "1F388", emoji: "🎈" },
];
