export const ENGLISH_ALIASES: Record<string, string[]> = {
  "alkoholfri öl": ["non alcoholic beer", "alcohol free beer"],
  "allrent": ["all purpose cleaner", "multi surface cleaner", "surface cleaner"],
  "aluminiumfolie": ["aluminium foil", "aluminum foil", "tin foil", "foil"],
  "ananas": ["pineapple", "pineapples"],
  "apelsin": ["orange", "oranges"],
  "apelsinjuice": ["orange juice"],
  "aubergine": ["aubergines", "eggplant", "eggplants"],
  "avokado": ["avocado", "avocados"],
  "baguette": ["baguettes"],
  "bakchoklad": ["baking chocolate", "cooking chocolate"],
  "bakplåtspapper": ["baking paper", "parchment paper", "baking parchment"],
  "bakpulver": ["baking powder"],
  "ballonger": ["balloons"],
  "balsam": ["conditioner", "hair conditioner"],
  "banan": ["banana", "bananas"],
  "barbecuesås": ["barbecue sauce", "bbq sauce"],
  "barnmat": ["baby food"],
  "barnschampo": ["baby shampoo", "kids shampoo"],
  "basmatiris": ["basmati rice"],
  "batterier": ["batteries"],
  "bearnaisesås": ["bearnaise sauce", "bearnaise"],
  "bikarbonat": ["baking soda", "bicarbonate of soda", "bicarb"],
  "bindor": ["sanitary pads", "sanitary towels"],
  "björnbär": ["blackberries", "blackberry"],
  "blandfärs": ["mixed mince", "mixed minced meat"],
  "blodpudding": ["black pudding", "blood pudding"],
  "blomkål": ["cauliflower"],
  "blommor": ["flowers"],
  "blåbär": ["blueberries", "blueberry"],
  "blöjor": ["diapers", "nappies"],
  "blöjpåsar": ["nappy sacks", "nappy bags"],
  "bovete": ["buckwheat"],
  "bryggkaffe": ["filter coffee", "ground coffee"],
  "bulgur": ["bulgur wheat"],
  "buljongtärningar": ["stock cubes", "bouillon cubes", "stock cube"],
  "chai te": ["chai tea", "chai"],
  "champinjon": ["mushroom", "mushrooms", "button mushrooms", "white mushrooms"],
  "chili": ["chilli", "chili pepper", "chillies"],
  "chilipulver": ["chili powder", "chilli powder"],
  "chilisås": ["chili sauce", "chilli sauce"],
  "chips": ["crisps", "potato chips"],
  "chokladkaka": ["chocolate bar", "bar of chocolate"],
  "chokladmjölk": ["chocolate milk"],
  "citron": ["lemon", "lemons"],
  "clementin": ["clementine", "clementines"],
  "crème fraiche": ["creme fraiche"],
  "curry": ["curry powder"],
  "deodorant": ["antiperspirant"],
  "diskborste": ["dish brush", "washing up brush"],
  "diskmaskinstabletter": ["dishwasher tablets", "dishwasher tabs", "dishwasher detergent"],
  "diskmedel": ["washing up liquid", "dish soap", "dishwashing liquid", "dish detergent"],
  "disksvamp": ["dish sponge", "washing up sponge", "sponge"],
  "duschtvål": ["shower gel", "body wash"],
  "energidryck": ["energy drink", "energy drinks"],
  "engångsgrill": ["disposable grill", "disposable barbecue", "disposable bbq"],
  "engångshandskar": ["disposable gloves", "plastic gloves"],
  "engångsmatlådor": ["disposable food containers", "disposable containers"],
  "entrecote": ["ribeye", "rib eye"],
  "falafel": ["falafels"],
  "farinsocker": ["brown sugar", "soft brown sugar"],
  "fiskbullar": ["fish balls"],
  "fiskfoder": ["fish food"],
  "fiskpinnar": ["fish fingers", "fish sticks"],
  "florsocker": ["icing sugar", "powdered sugar", "confectioners sugar"],
  "fläskfilé": ["pork tenderloin", "pork fillet"],
  "fläskfärs": ["ground pork", "minced pork", "pork mince"],
  "fläskkotlett": ["pork chop", "pork chops"],
  "folköl": ["beer"],
  "formbröd": ["bread", "loaf of bread", "sliced bread", "sandwich loaf"],
  "fralla": ["bread roll", "bread rolls", "rolls"],
  "fruktpuré": ["fruit puree"],
  "fryspåsar": ["freezer bags"],
  "fryst grönsaksblandning": ["frozen vegetables", "frozen mixed vegetables", "frozen vegetable mix"],
  "fryst majs": ["frozen corn", "frozen sweetcorn"],
  "fryst pizza": ["frozen pizza", "frozen pizzas"],
  "fryst smoothieblandning": ["frozen smoothie mix", "frozen smoothie blend"],
  "fryst smördeg": ["puff pastry", "frozen puff pastry"],
  "fryst spenat": ["frozen spinach"],
  "frysta bullar": ["frozen buns"],
  "frysta bär": ["frozen berries"],
  "frysta köttbullar": ["frozen meatballs"],
  "frysta räkor": ["frozen shrimp", "frozen prawns"],
  "frysta ärter": ["frozen peas", "peas"],
  "fågelfrö": ["bird seed", "birdseed"],
  "färdigsallad": ["ready made salad", "prepared salad"],
  "fönsterputs": ["window cleaner", "glass cleaner"],
  "glasnudlar": ["glass noodles", "cellophane noodles"],
  "glass": ["ice cream"],
  "glasspinnar": ["ice lollies", "popsicles", "ice pops"],
  "grahamsmjöl": ["graham flour", "wholemeal flour", "whole wheat flour"],
  "grapefrukt": ["grapefruit", "grapefruits"],
  "gratäng": ["gratin"],
  "gravlax": ["gravadlax", "cured salmon"],
  "grädde": ["cream"],
  "gräddfil": ["sour cream"],
  "grönt te": ["green tea"],
  "grötpulver": ["baby porridge", "baby cereal"],
  "grötris": ["pudding rice", "porridge rice"],
  "gul lök": ["yellow onion", "yellow onions", "brown onion", "brown onions"],
  "gurka": ["cucumber", "cucumbers"],
  "hallon": ["raspberries", "raspberry"],
  "hamburgerbröd": ["burger buns", "hamburger buns", "burger bun"],
  "handsprit": ["hand sanitiser", "hand sanitizer", "hand gel"],
  "havredryck": ["oat milk", "oat drink"],
  "havregryn": ["oats", "rolled oats", "porridge oats"],
  "havremjöl": ["oat flour"],
  "hel kyckling": ["whole chicken", "whole chickens"],
  "honung": ["honey"],
  "hundgodis": ["dog treats"],
  "hundmat": ["dog food"],
  "hushållspapper": ["paper towels", "kitchen roll", "kitchen towel"],
  "ingefära": ["ginger", "fresh ginger", "root ginger"],
  "isbergssallad": ["iceberg lettuce", "lettuce", "iceberg"],
  "isbitar": ["ice cubes", "ice"],
  "jasminris": ["jasmine rice"],
  "jordgubbar": ["strawberries", "strawberry"],
  "jordnötssmör": ["peanut butter"],
  "julskinka": ["christmas ham"],
  "jäst": ["yeast"],
  "kaffebönor": ["coffee beans"],
  "kaffekapslar": ["coffee pods", "coffee capsules"],
  "kakao": ["cocoa", "cocoa powder"],
  "kalkonfilé": ["turkey breast", "turkey breasts", "turkey fillet"],
  "kalkonpålägg": ["sliced turkey", "turkey slices"],
  "kanel": ["cinnamon"],
  "kanelbulle": ["cinnamon bun", "cinnamon buns", "cinnamon roll", "cinnamon rolls"],
  "kardemumma": ["cardamom"],
  "karré": ["pork collar", "pork neck"],
  "kattmat": ["cat food"],
  "kattsand": ["cat litter"],
  "kebabtallrik": ["kebab plate"],
  "keso": ["cottage cheese"],
  "ketchup": ["tomato ketchup"],
  "kex": ["biscuits", "crackers"],
  "kidneybönor": ["kidney beans"],
  "kikärtor": ["chickpeas", "garbanzo beans"],
  "kiwi": ["kiwis", "kiwi fruit"],
  "knäckebröd": ["crispbread", "crisp bread"],
  "koffeinfritt kaffe": ["decaf coffee", "decaffeinated coffee", "decaf"],
  "kokosflingor": ["desiccated coconut", "shredded coconut", "coconut flakes"],
  "kokosmjölk": ["coconut milk"],
  "kokt skinka": ["cooked ham", "boiled ham"],
  "kola": ["toffee"],
  "korvbröd": ["hot dog buns", "hot dog rolls", "hotdog buns"],
  "krossade tomater": ["crushed tomatoes", "chopped tomatoes", "tinned tomatoes", "canned tomatoes"],
  "kräftor": ["crayfish", "crawfish"],
  "kvarg": ["quark"],
  "kycklingfilé": ["chicken breast", "chicken breasts", "chicken fillet"],
  "kycklinglårfilé": ["chicken thigh fillet", "chicken thigh fillets", "chicken thighs", "chicken thigh"],
  "kycklingnuggets": ["chicken nuggets", "nuggets"],
  "körsbär": ["cherries", "cherry"],
  "körsbärstomat": ["cherry tomato", "cherry tomatoes"],
  "köttbullar": ["meatballs", "meatball"],
  "köttfärs": ["minced meat", "ground meat", "mince"],
  "lagerblad": ["bay leaves", "bay leaf"],
  "lakrits": ["liquorice", "licorice"],
  "lammfärs": ["ground lamb", "minced lamb", "lamb mince"],
  "lammkotlett": ["lamb chop", "lamb chops"],
  "lasagneplattor": ["lasagne sheets", "lasagna sheets", "lasagna noodles"],
  "lax": ["salmon", "salmon fillet", "salmon fillets"],
  "leverkorv": ["liver sausage", "liverwurst"],
  "leverpastej": ["liver pate", "liver paste"],
  "lime": ["limes"],
  "lingonsylt": ["lingonberry jam"],
  "linser": ["lentils"],
  "läsk": ["soda", "soft drink", "soft drinks", "fizzy drink"],
  "lättläsk": ["diet soda", "diet soft drink", "sugar free soda"],
  "lättmjölk": ["low fat milk", "skimmed milk", "skim milk"],
  "lök": ["onion", "onions"],
  "lösgodis": ["pick and mix", "loose candy", "loose sweets"],
  "majonnäs": ["mayonnaise", "mayo"],
  "majs": ["corn", "sweetcorn", "sweet corn", "maize"],
  "mandel": ["almonds", "almond"],
  "mandeldryck": ["almond milk", "almond drink"],
  "mandelmjöl": ["almond flour", "ground almonds"],
  "mango": ["mangoes", "mangos"],
  "margarin": ["margarine"],
  "matavfallspåsar": ["food waste bags", "compost bags"],
  "matlagningsgrädde": ["cooking cream"],
  "matolja": ["cooking oil", "vegetable oil"],
  "mellanmjölk": ["semi skimmed milk"],
  "melon": ["melons"],
  "mineralvatten": ["sparkling water", "mineral water", "fizzy water"],
  "mjöl": ["flour"],
  "mjölk": ["milk"],
  "morot": ["carrot", "carrots"],
  "muffinsform": ["muffin cases", "cupcake liners", "muffin liners"],
  "muskot": ["nutmeg"],
  "musslor": ["mussels", "mussel"],
  "nappar": ["pacifiers", "dummies"],
  "nektarin": ["nectarine", "nectarines"],
  "nudlar": ["noodles"],
  "nötfärs": ["ground beef", "minced beef", "beef mince"],
  "nötter": ["nuts"],
  "O'boy": ["hot chocolate", "drinking chocolate"],
  "olivolja": ["olive oil"],
  "olja": ["oil"],
  "ost": ["cheese"],
  "ostbågar": ["cheese puffs", "cheese doodles"],
  "panerad fisk": ["breaded fish"],
  "paprika": ["bell pepper", "bell peppers", "capsicum", "sweet pepper"],
  "paprikapulver": ["paprika powder", "ground paprika"],
  "parmesan": ["parmesan cheese"],
  "passerade tomater": ["passata", "sieved tomatoes", "strained tomatoes"],
  "pastasallad": ["pasta salad"],
  "peppar": ["black pepper", "pepper", "peppercorns"],
  "pepparkakor": ["gingerbread", "gingerbread cookies", "ginger snaps"],
  "persika": ["peach", "peaches"],
  "persilja": ["parsley", "fresh parsley"],
  "pitabröd": ["pita bread", "pita", "pitas"],
  "plastfolie": ["cling film", "clingfilm", "plastic wrap", "saran wrap"],
  "plommon": ["plum", "plums"],
  "plåster": ["plasters", "band aids", "bandaids"],
  "pommes frites": ["french fries", "fries", "oven chips"],
  "potatis": ["potatoes", "potato"],
  "potatismjöl": ["potato flour", "potato starch"],
  "potatismos": ["mashed potatoes", "mashed potato", "instant mash"],
  "prosciutto": ["parma ham"],
  "proteindryck": ["protein drink", "protein shake"],
  "purjolök": ["leek", "leeks"],
  "pärlsocker": ["pearl sugar"],
  "päron": ["pear", "pears"],
  "rakhyvel": ["razor", "razors"],
  "revbensspjäll": ["spare ribs", "spareribs", "pork ribs", "ribs"],
  "rooibos te": ["rooibos tea", "rooibos"],
  "rostbiff": ["roast beef"],
  "russin": ["raisins"],
  "rågbröd": ["rye bread"],
  "rågmjöl": ["rye flour"],
  "räkor": ["shrimp", "shrimps", "prawns", "prawn"],
  "rödbeta": ["beetroot", "beetroots", "beets", "beet"],
  "rödlök": ["red onion", "red onions"],
  "rökt lax": ["smoked salmon"],
  "saffran": ["saffron"],
  "saft": ["cordial", "fruit cordial"],
  "saltade jordnötter": ["salted peanuts"],
  "saltstänger": ["pretzel sticks"],
  "schampo": ["shampoo"],
  "senap": ["mustard"],
  "senapssill": ["mustard herring"],
  "servetter": ["napkins", "serviettes"],
  "sill": ["herring", "pickled herring"],
  "skinka": ["ham"],
  "skorpor": ["rusks"],
  "sköljmedel": ["fabric softener", "fabric conditioner"],
  "smoothie": ["smoothies"],
  "smör": ["butter"],
  "snabbkaffe": ["instant coffee"],
  "socker": ["sugar"],
  "soja": ["soy sauce", "soya sauce"],
  "solkräm": ["sunscreen", "sun cream", "sunblock"],
  "soppa": ["soup", "soups"],
  "soppåsar": ["bin bags", "trash bags", "garbage bags", "bin liners"],
  "spenat": ["spinach"],
  "sportdryck": ["sports drink", "sports drinks"],
  "stearinljus": ["candles", "candle"],
  "ströbröd": ["breadcrumbs", "bread crumbs"],
  "surdegsbröd": ["sourdough", "sourdough bread"],
  "svart te": ["black tea"],
  "sylta": ["head cheese", "brawn"],
  "tamponger": ["tampons"],
  "tandborste": ["toothbrush"],
  "tandkräm": ["toothpaste"],
  "tidning": ["newspaper"],
  "timjan": ["thyme"],
  "toapapper": ["toilet paper", "toilet roll", "loo roll"],
  "tomat": ["tomato", "tomatoes"],
  "tomatpuré": ["tomato paste"],
  "tonfisk": ["tuna", "canned tuna", "tinned tuna"],
  "torkad basilika": ["dried basil"],
  "torkad dill": ["dried dill"],
  "torsk": ["cod", "cod fillet", "cod fillets"],
  "tortillabröd": ["tortillas", "tortilla", "wraps"],
  "tuggummi": ["chewing gum", "gum"],
  "tvål": ["soap", "hand soap", "bar of soap"],
  "tvättmedel": ["laundry detergent", "washing powder", "laundry powder"],
  "tändstickor": ["matches"],
  "vaniljsocker": ["vanilla sugar"],
  "vatten": ["water", "bottled water", "still water"],
  "vattenmelon": ["watermelon", "watermelons"],
  "vetemjöl": ["wheat flour", "plain flour", "all purpose flour"],
  "vindruvor": ["grapes", "grape"],
  "vispgrädde": ["whipping cream", "heavy cream"],
  "vita bönor": ["white beans"],
  "vitkål": ["white cabbage", "cabbage"],
  "vitlök": ["garlic", "garlic cloves"],
  "vitlökspulver": ["garlic powder"],
  "våtservetter": ["wet wipes", "wipes"],
  "wc-rent": ["toilet cleaner", "toilet bowl cleaner"],
  "wienerbröd": ["danish pastry", "danish pastries"],
  "wienerkorv": ["frankfurters", "wieners", "hot dog sausages"],
  "yoghurt": ["yogurt"],
  "zucchini": ["zucchinis", "courgette", "courgettes"],
  "ägg": ["eggs", "egg"],
  "äppeljuice": ["apple juice"],
  "äpple": ["apple", "apples"],
};